language: r
cache: packages
pandoc_version: 1.19.2.1

env:
  global:
    - secure: AM8M6Uj5rb0ZgJ5VRFxp+gF7BxKdAccH3TNJfBJYmcIBdV9EFifwgzWz89ye1U37s7IZvQesAfy7DFaqHi6E861i8NsWwqJMrHInYou0Bjn3xUscqTYNCxk+loHiiSdWT9EvfLl20RrEhVG6NBW4iqs4iJuPEzX1tl8GT3FrKi7090Q18B3DStAHQWk0ufQT7fjY/ASfkx+Mj19dmrfNvTV9wOfE2sRZ7AvsKjvPL/kHKJCGv5+SZzQtFczAT7JPnV/LukBGREsEdAWr6bBLZ/iFoJ0eSooNERMBdk+YWrTAfQw3A1QfXgF0P8AgkmSJNnkb0KJbzsL7M1RYaUk2JPXr+f8d/1apuYFMkAulVbkdGUJz1lYihWTUIPIqO0PcVYkrfDmZ5bC+8XT9c9fQ9/7+iVnQnl9nwUwfo3Gl/qz5DhQDVXscZN7uGGn2v15mBzWrxxa8ch5PxFHkHJFJ2QiDdnBxJhSBya61/L6Yq9zQdgn3sUCUJlr+7sWRDHRQtv35a+/M35McNabN9roDhOlzjl6djnjAGsYqUOpyPvvpJ5CUc3VL9lmgTiF7PlsTfLy2tDeScERXXroYd8XsZ9M6n8uilsTwhAgTMspj/3P2C5QS0DN+29Xds3C4lx1rvvLHG5f4yhiwjduHUTpAUMj7rPIsahgJg8bpXqKUXOA=

before_script:
  - chmod +x ./_build.sh
  - chmod +x ./_deploy.sh

script:
  - ./_build.sh
  - ./_deploy.sh

branches:
  only:
    - master